### ISSUE TITLE
Need to clean out invalid characters

### ISSUE THREAD

**Issue by that0n3guy** [spmorton/Myth-Scripts#1]
Hello,

I tried transfering a video today called "K-19: The Widowmaker" to "K-19: The Widowmaker (1895)/K-19: The Widowmaker.mpg" and it errors out at "Performing copy validation"... 

I'm guessing this is because the filename/foldername has a colon in it (because the name of the movie does).

I think invalid should be stripped out of filename/path string.  Things that need stripped out are:

Tilde (~)
Number sign (#)
Percent (%)
Ampersand (&)
Asterisk (*)
Braces ({ })
Backslash ()
Colon (:)
Angle brackets (< >)
Question mark (?)
Slash (/)
Plus sign (+)
Pipe (|)
Quotation mark (")

**Comment by peterdv** [comment]
I was just beginning to wonder (forgive me, it is early morning): at which level in the software stack should validity be ensured.

The reason I find this interesting is, that several of the characters mentioned above are legal and useful characters in file (and path) names on my particular file system, so which characters to allow is highly dependant on the particular software environment.

On a practical level, how to propose a sensible file name ?

I like what I see in general. Grab the title, construct a file name. Ok what to do then when this fails on a particular operating system using a particular file system ? Should one 1) Be restrictive and up front forbid all characters ever known to have caused problems; 2) Catch the error and attempt an automated correction; 3) Fail and give the user an option to specify the file name (possibly on the command line).

Well, clearly this implementation has chosen 3), You can easily modify TVFMT and/or MVFMT in lines 29 and 32 to suit Your particular needs. You might add an OptionGroup to handle "Target Definition", and submit a patch.

Personally I strongly dislike 1), why make features unavailable to everyone just because it causes a problem for a limited group of file systems ?

I have implemented 2) in many situations previously, but personally I have never been satisfied with the result. The problem must clearly be detected and reported by the file system, it is the only authoritative source of what constitutes a legal file name. Then how to perform an efficient error correction at a much higher level in the software stack usually just having received a generic exception "illegal filename" - how to get access to the knowledge hidden several layers below of what constitutes a legal file name - or where the error actually is in the proposed file name ? I do not find 3) possibly argumented with an installation dependent configuration parameter holding a local negative list of forbidden characters ....

**Comment by peterdv** [comment]
Forgive me, it IS early. Please read:

I do not find 3) a bad choice, possibly argumented with an installation dependent configuration parameter holding a local negative list of forbidden characters ....

**Comment by spmorton** [comment]
Failure on the copy validation is probably not because of the file name, many things can fail the process, in particular certain foreign characters in names have cause many issues for me resulting in the script aborting the process. try running the script manually, you will find more detail is available to determine the error. 

I will look into the script continuing the validation on a failed copy and see if I can error out the entire process on any failure.

P.S. Sorry for the delay I didn't even realize this part of the site existed

**Comment by spmorton** [comment]
So in reexamining the script, here is the section giving the error
<code>
 def check_hash(self):
        self.log(self.log.GENERAL, self.log.INFO,
                 'Performing copy validation.')
        srchash = self.bend.getHash(self.rec.basename, self.rec.storagegroup)
        dsthash = self.bend.getHash(self.vid.filename, 'Videos')
        if srchash != dsthash:
            return False
        else:
            return True
</code>

If I recall correctly, there is a python library that has to be loaded in order to perform the hash look-ups, I believe it is python-pycrypto (opensuse 12.3). There could be other dependencies and I would suggest you refer to the myth python documentation.

**Comment by spmorton** [comment]
really dated issue
